kind: pipeline
type: docker
name: block_duplicated_pr_merged

steps:
- name: current_hollaex_cli_version
  image: alpine
  commands:
  -  export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags_current
  -  echo "Current Release tag is :" && cat .tags_current

- name: previous_hollaex_cli_version
  image: byrnedo/alpine-curl
  commands:
  -  curl https://raw.githubusercontent.com/bitholla/hollaex-cli/master/version > .tags_previous
  -  echo "The previous master release tag is :" && cat .tags_previous

- name: version_comparison
  image: frolvlad/alpine-bash
  commands:
  -  export TAGS_CURRENT=$(cat .tags_current) && export TAGS_PREVIOUS=$(cat .tags_previous) && if [ "$TAGS_PREVIOUS" ==  "$TAGS_CURRENT" ]; then echo "Blocking the merge since the versions are same..." && exit 1; else echo "Good to proceed"; fi

- name: slack_noti_job_end
  image: plugins/slack
  settings:
    channel: deployment
    webhook:
      from_secret: slack_webhook
  when:
    status: [failure]
  
trigger:
  branch: 
    - master
  event:
    - pull_request

---

kind: pipeline
type: docker
name: releaes_notification

steps:

- name: notify_job_start
  image: plugins/slack
  settings:
    template: "<{{build.link}}|HollaEx CLI merge> - #{{build.number}} started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook_from_vault
  
- name: docker_tag_for_release_testnet
  image: alpine
  commands:
  -  export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION-testnet" > .tags
  - echo "Current Release tag is :" && cat .tags
  when:
    branch: develop

- name: docker_tag_for_release_master
  image: alpine
  commands:
  -  export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags
  - echo "Current Release tag is :" && cat .tags
  when:
    branch: master

- name: create_github_release
  image: bitholla/devops-tools:drone_github_hub-2004241546
  environment:
    GITHUB_TOKEN:
      from_secret: github_oauth2_token_for_releases
  commands:
    - apt-get update && apt-get install -y hub git
    - hub release create -m "HollaEx CLI v$(cat .tags) Release" -t ${DRONE_BRANCH} $(cat .tags)
  when:
    branch: master

- name: notify_job_done
  image: bitholla/devops-tools:drone_slack-8a15f61
  channel: deployment
  environment:
    SLACK_WEBHOOK:
      from_secret: slack_webhook_from_vault
  when:
    status: [ success, failure ]

- name: notify_to_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.4
  channel: deployment
  environment:
    WEBHOOK_URL:
      from_secret: webhook_url_from_vault
  when:
    status: [ success, failure ]

- name: notify_to_discord_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.5
  channel: deployment
  settings:
    target: discord
    release_name: hollaex-cli
  environment:
    WEBHOOK_URL:
      from_secret: discord_webhook_url
  when:
    status: [ success, failure ]
    branch: master
  
trigger:
  branch: 
    - master
    - testnet
    - develop
  event:
    - push

---
kind: secret
name: slack_webhook_from_vault
get:
  path: devops/data/drone-ci/secret
  name: slack_webhook

---
kind: secret
name: webhook_url_from_vault
get:
  path: devops/data/drone-ci/secret
  name: webhook_url
