kind: pipeline
type: docker
name: block_duplicated_pr_merged

steps:
- name: current_hollaex_cli_version
  image: alpine
  commands:
  -  export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags_current
  -  echo "Current Release tag is :" && cat .tags_current

- name: previous_hollaex_cli_version
  image: byrnedo/alpine-curl
  commands:
  -  curl https://raw.githubusercontent.com/bitholla/hollaex-cli/master/version > .tags_previous
  -  echo "The previous master release tag is :" && cat .tags_previous

- name: version_comparison
  image: frolvlad/alpine-bash
  commands:
  -  export TAGS_CURRENT=$(cat .tags_current) && export TAGS_PREVIOUS=$(cat .tags_previous) && if [ "$TAGS_PREVIOUS" ==  "$TAGS_CURRENT" ]; then echo "Blocking the merge since the versions are same..." && exit 1; else echo "Good to proceed"; fi

- name: slack_noti_job_end
  image: plugins/slack
  settings:
    channel: deployment
    webhook:
      from_secret: slack_webhook
  when:
    status: [failure]
  
trigger:
  branch: 
    - master
  event:
    - pull_request

---

kind: pipeline
type: docker
name: releaes_notification

steps:

# - name: notify_job_start
#   image: plugins/slack
#   settings:
#     template: "<{{build.link}}|HollaEx CLI merge> - #{{build.number}} started on <https://github.com/{{repo.owner}}/{{repo.name}}/tree/{{build.branch}}|{{repo.name}} / {{build.branch}}> by {{build.author}}"
#   channel: deployment
#   environment:
#     SLACK_WEBHOOK:
#       from_secret: slack_webhook
  
- name: docker_tag_for_release_testnet
  image: alpine
  commands:
  -  export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION-testnet" > .tags
  - echo "Current Release tag is :" && cat .tags
  when:
    branch: testnet

# test
- name: docker_tag_for_release_develop
  image: alpine
  commands:
  - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION-develop" > .tags
  - echo "Current Release tag is :" && cat .tags
  when:
    branch: develop

# - name: docker_build
#   image: plugins/docker
#   settings:
#     repo: bitholla/hollaex-cli
#     dockerfile: docker/Dockerfile
#     username:
#       from_secret: docker_username
#     password:
#       from_secret: docker_password
#   when:
#     branch: develop

- name: testnet_dct_signing
  image: docker:20.10-dind
  privileged: true
  environment:
    DOCKER_USERNAME:
      from_secret: docker_username_yechan
    DOCKER_PASSWORD:
      from_secret: docker_password_yechan
    DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE:
      from_secret: DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE
    DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE:
      from_secret: DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE
    DOCKER_CONTENT_TRUST_PRIVATE_KEY:
      from_secret: DOCKER_CONTENT_TRUST_PRIVATE_KEY
    DOCKER_CONTENT_TRUST_PUBLIC_KEY:
      from_secret: DOCKER_CONTENT_TRUST_PUBLIC_KEY
  volumes:
    - name: docker
      path: /var/run/docker.sock
  commands:
    - docker login -u $${DOCKER_USERNAME} -p $${DOCKER_PASSWORD}
    - export DOCKER_CLI_EXPERIMENTAL=enabled
    - export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION-develop" > .tags
    - docker pull bitholla/hollaex-cli:$(cat .tags)
    - export DOCKER_CONTENT_TRUST=1
    - mkdir $HOME/.docker/trust && mkdir $HOME/.docker/trust/private
    - echo -n $${DOCKER_CONTENT_TRUST_PRIVATE_KEY} | base64 -d > $HOME/.docker/trust/private/997ecb83770cb33bb1d77f4321c7ac48608df95b947b370b869cc2b8a03e5de9.key
    - echo -n $${DOCKER_CONTENT_TRUST_PUBLIC_KEY} | base64 -d > bitholla-cicd.pub
    - chmod 600 $HOME/.docker/trust/private/997ecb83770cb33bb1d77f4321c7ac48608df95b947b370b869cc2b8a03e5de9.key
    - chmod 600 bitholla-cicd.pub
    - docker trust key load $HOME/.docker/trust/private/997ecb83770cb33bb1d77f4321c7ac48608df95b947b370b869cc2b8a03e5de9.key --name bitholla-cicd
    - docker trust signer add --key bitholla-cicd.pub bitholla-cicd bitholla/hollaex-cli
    - docker trust sign bitholla/hollaex-cli:$(cat .tags)

- name: docker_tag_for_release_master
  image: alpine
  commands:
  -  export PACKAGE_VERSION="$(cat version)" && echo "$PACKAGE_VERSION" > .tags
  - echo "Current Release tag is :" && cat .tags
  when:
    branch: master
    
- name: create_github_release
  image: bitholla/devops-tools:drone_github_hub-2004241546
  environment:
    GITHUB_TOKEN:
      from_secret: github_oauth2_token_for_releases
  commands:
    - apt-get update && apt-get install -y hub git
    - hub release create -m "HollaEx CLI v$(cat .tags) Release" -t ${DRONE_BRANCH} $(cat .tags)
  when:
    branch: master

# - name: notify_job_done
#   image: bitholla/devops-tools:drone_slack-8a15f61
#   channel: deployment
#   environment:
#     SLACK_WEBHOOK:
#       from_secret: slack_webhook
#   when:
#     status: [ success, failure ]

- name: notify_to_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.4
  channel: deployment
  environment:
    WEBHOOK_URL:
      from_secret: webhook_url
  when:
    status: [ success, failure ]

- name: notify_to_discord_releases
  image: bitholla/devops-tools:drone_partymaker-0.1.5
  channel: deployment
  settings:
    target: discord
    release_name: hollaex-cli
  environment:
    WEBHOOK_URL:
      from_secret: discord_webhook_url
  when:
    status: [ success, failure ]
    branch: master

volumes:
  - name: docker
    host:
      path: /var/run/docker.sock

trigger:
  branch: 
    - master
    - testnet
    - develop
  event:
    - push

---
kind: secret
name: slack_webhook
get:
  path: devops/data/drone-ci/secret
  name: slack_webhook

---
kind: secret
name: webhook_url
get:
  path: devops/data/drone-ci/secret
  name: webhook_url

---
kind: secret
name: discord_webhook_url
get:
  path: devops/data/drone-ci/secret
  name: discord_webhook_url

---
kind: secret
name: github_oauth2_token_for_releases
get:
  path: devops/data/drone-ci/secret
  name: github_oauth2_token_for_releases

---
kind: secret
name: DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE
get:
  path: devops/data/drone-ci/secret
  name: DOCKER_CONTENT_TRUST_REPOSITORY_PASSPHRASE

---
kind: secret
name: DOCKER_CONTENT_TRUST_PRIVATE_KEY
get:
  path: devops/data/drone-ci/secret
  name: DOCKER_CONTENT_TRUST_PRIVATE_KEY

---
kind: secret
name: DOCKER_CONTENT_TRUST_PUBLIC_KEY
get:
  path: devops/data/drone-ci/secret
  name: DOCKER_CONTENT_TRUST_PUBLIC_KEY

---
kind: secret
name: DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE
get:
  path: devops/data/drone-ci/secret
  name: DOCKER_CONTENT_TRUST_ROOT_PASSPHRASE