{{- if .Values.job.enable }}

apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: {{.Release.Name}}
    role: {{.Release.Namespace}}
  name: {{.Release.Name}}
  namespace: {{.Release.Namespace}}
spec:
  template:
    spec:

{{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
{{- end }}

      containers:
      - name: {{.Release.Name}}
        image: {{.Values.imageRegistry}}:{{.Values.dockerTag}}
        command: ["/bin/bash", "-c"]

{{- if eq .Values.job.mode "add_coin" }}

        args:
          - node tools/dbs/addCoin.js;

{{- else if eq .Values.job.mode "remove_coin" }}

        args:
          - node tools/dbs/removeCoin.js;

{{- else if eq .Values.job.mode "add_pair" }}

        args:
          - node tools/dbs/addPair.js;

{{- else if eq .Values.job.mode "remove_pair" }}

        args:
          - node tools/dbs/removePair.js;

{{- else if eq .Values.job.mode "set_activation_code" }}

        args:
          - node tools/dbs/setActivationCode.js;

{{- else if eq .Values.job.mode "check_constants" }}

        args:
          - node tools/dbs/checkConstants.js;

{{- else if eq .Values.job.mode "set_config" }}

        args:
          - node tools/dbs/setConfig.js;

{{- else if eq .Values.job.mode "set_security" }}

        args:
          - node tools/dbs/setSecurity.js;

{{- else if eq .Values.job.mode "hollaex_upgrade" }}

        args:
          - sequelize db:migrate;
            node tools/dbs/runTriggers.js;
            node tools/dbs/checkConfig.js;
            node tools/dbs/setKitVersion.js;

{{- end }}

        imagePullPolicy: Always

        envFrom:
          - configMapRef:
              name: {{.Values.envName}}
          - secretRef:
              name: {{.Values.secretName}}
        
        env:

{{- if eq .Values.job.mode "add_coin" }}

          - name: COIN_SYMBOL
            value: {{.Values.job.env.coin_symbol}}
          - name: COIN_FULLNAME
            value: {{.Values.job.env.coin_fullname}}
          - name: COIN_ALLOW_DEPOSIT
            value: {{.Values.job.env.coin_allow_deposit | quote }}
          - name: COIN_ALLOW_WITHDRAWAL
            value: {{.Values.job.env.coin_allow_withdrawal | quote }}
          - name: COIN_WITHDRAWAL_FEE
            value: {{.Values.job.env.coin_withdrawal_fee | quote }}
          - name: COIN_MIN
            value: {{.Values.job.env.coin_min | quote }}
          - name: COIN_MAX
            value: {{.Values.job.env.coin_max | quote }}
          - name: COIN_INCREMENT_UNIT
            value: {{.Values.job.env.coin_increment_unit | quote }}
          - name: COIN_DEPOSIT_LIMITS
            value: {{.Values.job.env.coin_deposit_limits | quote}}
          - name: COIN_WITHDRAWAL_LIMITS
            value: {{.Values.job.env.coin_withdrawal_limits | quote }}
          - name: COIN_ACTIVE
            value: {{.Values.job.env.coin_active | quote }}

{{- else if eq .Values.job.mode "remove_coin" }}

          - name: COIN_SYMBOL
            value: {{.Values.job.env.coin_symbol}}

{{- else if eq .Values.job.mode "add_pair" }}

          - name: PAIR_NAME
            value: {{.Values.job.env.pair_name}}
          - name: PAIR_BASE
            value: {{.Values.job.env.pair_base}}
          - name: PAIR_2
            value: {{.Values.job.env.pair_2}}
          - name: TAKER_FEES
            value: {{.Values.job.env.taker_fees | quote }}
          - name: MAKER_FEES
            value: {{.Values.job.env.maker_fees | quote }}
          - name: MIN_SIZE
            value: {{.Values.job.env.min_size | quote }}
          - name: MAX_SIZE
            value: {{.Values.job.env.max_size | quote }}
          - name: MIN_PRICE
            value: {{.Values.job.env.min_price | quote }}
          - name: MAX_PRICE
            value: {{.Values.job.env.max_price | quote }}
          - name: INCREMENT_SIZE
            value: {{.Values.job.env.increment_size | quote }}
          - name: INCREMENT_PRICE
            value: {{.Values.job.env.increment_price | quote }}
          - name: PAIR_ACTIVE
            value: {{.Values.job.env.pair_active | quote }}

{{- else if eq .Values.job.mode "remove_pair" }}

          - name: PAIR_NAME
            value: {{.Values.job.env.pair_name}}

{{- else if eq .Values.job.mode "set_activation_code" }}

          - name: ACTIVATION_CODE
            value: "{{.Values.job.env.activation_code}}"

{{- else if eq .Values.job.mode "set_security" }}

          - name: ALLOWED_DOMAINS
            value: "{{.Values.job.env.allowed_domains}}"
          - name: ADMIN_WHITELIST_IP
            value: "{{.Values.job.env.admin_whitelist_ip}}"
          - name: CAPTCHA_SITE_KEY
            value: "{{.Values.job.env.captcha_site_key}}"
          - name: CAPTCHA_SECRET_KEY
            value: "{{.Values.job.env.captcha_secret_key}}"

{{- end }}

        resources:
          limits:
            memory: "300Mi"
            cpu: "100m"
          requests:
            memory: "50Mi"
            cpu: "15m"

{{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
{{- end }}
      restartPolicy: Never
  backoffLimit: 0
{{- end }}