# Default values for bitholla-hollaex-nginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
imageRegistry: bitholla/hollaex-network
dockerTag:
  
imagePullSecrets:
  - name: docker-registry-secret

envName: hollaex-network-env
secretName: hollaex-network-secret

envCoinsName: hollaex-network-env-coins
envPairsName: hollaex-network-env-pairs

DEPLOYMENT_MODE: all

db_ssl: false

stable:
  replicaCount: 1
  
staging:
  enable: false
  replicaCount: 1
  dockerTag:

nodeSelector: {}

autoScaling:
  hpa:
    enable: false 
    memory:
      threshold: 80

podRestart_webhook_url: 

job:
  enable: false
  env:
    coin_code:
    pair_code:

cronjob:
  enable: false
  schedule: